name: CI

on: [push]

jobs:
  build:

    runs-on: shryke/texlive-ci-minimal

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make buildCI
    - name: Upload artifact
    - uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Main.pdf
        # Directory containing files to upload
        path: . 
